Fix bootstrapper mode efuses incoming connections - Keeping one spot available
Neptune-Crypto/neptune-core pull request #291
Opened 2024-12-14 14:58 UTC by elielnfinic

This PR fixes the issue of Bootstrapped nodes not able to accept incoming connections by always keeping one spot available by disconnected the longest lived connection. 
It addresses issue #287

2024-12-16 12:52 UTC, aszepieniec commented
Hi @elielnfinic, thanks for the PR.

It looks good: it's addressing the problem with a good fix. There is one thing I'm confused about though: why doesn't the error message match the one mentioned in the issue? For reference, the suggested change works around this `bail!` statement:

```
            bail!("Attempted to connect to more peers than allowed. Aborting connection.");
```

whereas the observed error message was "neptune_cash::main_loop: Got error: Refusing incoming connection. Reason: MaxPeerNumberExceeded".

Can you shed light on this discrepancy?

If not, maybe you fixed another, independent way to trigger the same error :D

2024-12-17 07:01 UTC, elielnfinic commented
Hello @aszepieniec, thanks for pointing that problem. I might have not understood the issue as it should be sorted out. My guess was to remove the longest lived peer before MAX is reached. 

I think another issue is on replicating the error. I am not able to replicate that issue. Could you please share how to replicate the error? I was trying spoofing the node with multiple connections but I might be wrong. As I could not replicate the issue, I went ahead and examined the code to say where I can insert the verification if the node is a bootstrap node.

Here is my script to try to connect multiple nodes to boostrap for them to discover one another : 

```sh
#!/bin/bash


BASE_DIR="$MY_PROJECT_PATH/neptune-core" 
BOOTSTRAP_PEER="127.0.0.1:9797"              
NODE_COUNT=30                                


BASE_PEER_PORT=8800
BASE_RPC_PORT=8900


launch_node() {
    NODE_ID=$1
    DATA_DIR="$BASE_DIR/data/node_$NODE_ID"
    PEER_PORT=$((BASE_PEER_PORT + NODE_ID))
    RPC_PORT=$((BASE_RPC_PORT + NODE_ID))

    echo "Launching node $NODE_ID..."
    mkdir -p "$DATA_DIR"  

   
    cargo run -- \
        --data-dir "$DATA_DIR" \
        --peer-port "$PEER_PORT" \
        --rpc-port "$RPC_PORT" \
        --peers "$BOOTSTRAP_PEER" \
        --max-num-peers 30  > "$DATA_DIR/node_$NODE_ID.log" 2>&1 &

    echo "Node $NODE_ID running with peer port $PEER_PORT and RPC port $RPC_PORT."
}


echo "Starting $NODE_COUNT nodes to connect to bootstrap peer $BOOTSTRAP_PEER..."


cd "$BASE_DIR" || { echo "Error: Directory $BASE_DIR does not exist!"; exit 1; }


for i in $(seq 1 $NODE_COUNT); do
    launch_node $i
    sleep 0.5  
done

echo "All nodes launched. Check logs in individual data directories under $BASE_DIR/data."
```

2024-12-17 15:55 UTC, elielnfinic commented
Ah, I see what you mean now. I wasn’t aware that `answer_peer_inner` also included a check, which could indeed result in two peers being disconnected. I’m currently reviewing the process to better understand the test changes you’re suggesting.

2024-12-21 02:16 UTC, elielnfinic commented
Per the the sequence you provided, I think I was able to fix the issue. By the way, my script had an error on the port which had to be set to the value `9798` but was `9797` and that's why I wasn't able to replicate the issue. After setting it to `9798`, I could replicate the issue. With the new commit, the initial issue appears to be fixed, please check it out.

Thank you.

2024-12-21 21:32 UTC, aszepieniec requested changes
You've managed to reproduce the issue, great! That's excellent progress.

About the proposed solution ... I'm afraid still skeptical.

Can you walk me through the logic of line 225?

```
        if global_state.net.peer_map.len() < (state.cli().max_num_peers - 1) as usize {
```

It reads like this if-body is being triggered whenever the peer map contains a number of peers that is less than max minus one. So:
 - If connected to zero peers, then send `DisconnectFromLongestLivedPeer` message.
 - If connected to one peer, then send `DisconnectFromLongestLivedPeer` message.
 - If connected to two peers, then send `DisconnectFromLongestLivedPeer` message.
 - ...
 - If connected to max-2 peers, then send `DisconnectFromLongestLivedPeer` message.
 - If connected to max-1 peers, then do nothing.
 - If connected to max peers, then do nothing.

The desired behavior is the opposite: the bootstrapper node should always be connected to max-1 peers. As long as it is connected to fewer peers, it retains those connections.

If I misunderstand, please clarify.

More fundamentally, I think you are repeating logic that's already present. The function `answer_peer_inner` calls `check_if_connection_is_allowed` on line 258. Towards the end of the function, line 138, there is a clause that is supposed to catch scenario in which a peer connects and the max number of peers will be reached as a result. If caught, the returned success code is `InternalConnectionStatus::AcceptedMaxReached` which then propagates back to `answer_peer_inner` who (line 286) sends a `DisconnectFromLongestLivedPeer` message.

The simplest way forward might be to figure out what's wrong with this code path and fix it. Alternatively, if you want to factor out this logic, and/or make it live elsewhere, please do. But right now there is logic duplication, which is not good.

2024-12-21 21:32 UTC, aszepieniec commented on src/connect_to_peers.rs
> +            info!("Bootsrap reached max peers, disconnecting longest lived peer");
```suggestion
            info!("Bootstrap reached max peers, disconnecting longest lived peer");
```

2024-12-22 11:26 UTC, aszepieniec commented
> I increased the sleep time in my script to 1 sec and this issue disappears so I believe its a concurrency issue.

This information is invaluable. Based on this analysis, the following scenario seems plausible / likely:

 - Two incoming connection requests are received simultaneously.
 - They are processed by different tasks, so they do not know about each other.
 - They both observe that the new connection would set the peer count to `max`. So they both generate a `AcceptedMaxReached` status code followed by a `DisconnectFromLongestLivedPeer` message sent to the main loop.
 - Before the first `DisconnectFromLongestLivedPeer` message is processed, the first peer is added to the peer map, setting the number of peers to `max`.
 - Before the first `DisconnectFromLongestLivedPeer` message is processed, the second connection handler attempts to add the second peer to the peer map, but as the max has already been reached this attempt fails and this failure results in the observed error message.

The root of the problem, as I see it, is that the peer map is read and then later modified within one thread/task, but another thread/task modifies it in the mean time.

Brainstorming for solutions:
 - Hold a write lock on the peer map for the entire peer loop setup. This prevents the second incoming request handler from starting until the first one is finished. The downside would be holding the write lock longer, preventing all other threads/tasks from progressing.
 - Stall before entering into the peer loop for however long it takes the main loop to process the `DisconnectFromLongestLivedPeer` message. This would require extra communication with extra `.await` steps.
 - Plow ahead, temporarily exceeding the max number of peers.

I invite @Sword-Smith and @dan-da to comment; both have much more experience than I do when it comes to concurrency.

2024-12-23 14:53 UTC, dan-da commented
> I invite @Sword-Smith and @dan-da to comment; both have much more experience than I do when it comes to concurrency.

I haven't been following this issue much, so just going from the analysis in https://github.com/Neptune-Crypto/neptune-core/pull/291#issuecomment-2558422487...

> Brainstorming for solutions:
> 
> * Hold a write lock on the peer map for the entire peer loop setup. This prevents the second incoming request handler from starting until the first one is finished. The downside would be holding the write lock longer, preventing all other threads/tasks from progressing.

bad for concurrency, my least favorite.  holding write-lock for longer (anywhere) is going the wrong direction.

> * Plow ahead, temporarily exceeding the max number of peers.

this seems best for concurrency.  I guess we could possibly exceed max by the number of simultaneous processing tasks.  So long as that doesn't pose a problem...

2025-01-05 20:54 UTC, elielnfinic commented
Instead of relying on the peers hashmap node and waiting for updates via mpsc (which I believe is causing delays), I introduced the `NUMBER_PEER_CONNECTIONS` `AtomicU16`. Based on the tests I conducted with a bootstrap node configured for a maximum of 20 peers receiving 50 and 100 connections, the results have been promising so far.

I also agree with @aszepieniec and @dan-da that temporarily exceeding the maximum number of peers could be a viable solution, but we may need to define clear boundaries for how far this can be extended.

Thank you!

2025-01-06 11:16 UTC, aszepieniec reviewed
This PR introduces a new asynchronous primitive for keeping track of the number of peers. While I am sure it improves the responsiveness and shrinks the window for race conditions, I am also concerned that it could also lead to inconsistent state and perhaps even deadlocks. @elielnfinic: please convince me that these concerns are unfounded. I also invite @dan-da to comment.

About the potential for deadlocks: I imagine this scenario
 - thread 1: acquire a write lock on global state then (attempts to) modify `NUMBER_PEER_CONNECTIONS`
 - thread 2: read `NUMBER_PEER_CONNECTIONS` then modify global state
 - result: both stall indefinitely waiting for the other's lock to be released

About inconsistent state: the distance between modifications to the `peer_map` and corresponding modifications to `NUMBER_PEER_CONNECTIONS` is quite large and things can go wrong in the mean time. In that case, the first modification goes through but the second one doesn't.

One more thing: the sanity of operations that use the peer map is checked in unit tests that use `peer_map.len()` to count the number of entries. Is there a way to expand the tests or modify them so that they capture `NUMBER_PEER_CONNECTIONS`? This line of though suggests that the variable should not be a static variable but live somewhere, perhaps on `GlobalStateLock`, which might even be extended with an accessor method `get_num_peer_connections()`.

2025-01-06 11:16 UTC, aszepieniec commented on src/connect_to_peers.rs
> +
We want to make it easy to verify that the number of entries in the `peer_map` and the value of `NUMBER_PEER_CONNECTIONS` is always in sync. To this end, let's add comments on top of all modifications to the `peer_map` where the corresponding modification to `NUMBER_PEER_CONNECTIONS` is happening. For this particular increment, please add the comment above the block 1449-1451 in `peer_loop.rs`/`PeerLoopHandler::run_wrapper`.

2025-01-06 11:57 UTC, aszepieniec commented
> I also agree with @aszepieniec and @dan-da that temporarily exceeding the maximum number of peers could be a viable solution, but we may need to define clear boundaries for how far this can be extended.

I made a PR implementing just this one change (#312). I invite your review. (For some reason I can't flag you as a reviewer.)

I'm not sure I understand what you mean by "we may need to define clear boundaries for how far this can be extended". Can you elaborate?

2025-01-06 13:50 UTC, elielnfinic commented on src/connect_to_peers.rs
> +
This is indeed a critical factor in ensuring a fast response, as sending the task and having it executed by the `main_loop` can take some time. I reviewed the Disconnect code in the `main_loop` to assess if there are scenarios where the operation might fail. I did not find any cases where the “disconnect longest-lived peer” logic would fail. Even in the rare instance that it does, since we no longer count peers using the hashmap length, it wouldn’t significantly impact the program. In the worst-case scenario, we might temporarily have hashmap MAX + 1, and the next peer connection attempt would also trigger the removal of the longest-lived peer again.

I agree with your proposed compromise to double-check if the main_loop operation succeeds. If it does not, we can re-increment the atomic variable to maintain consistency.

2025-01-06 13:53 UTC, elielnfinic commented on src/connect_to_peers.rs
> +
On that compromise, my fear is after we re-increment, we might get `MAX` or in worst case `MAX + n`,  n being the failed disconnects. But I think we can keep `MAX + n` in the hashmap if it fails exceeding the number of nodes temporarily - kinda this https://github.com/Neptune-Crypto/neptune-core/commit/f6ed30fa4ce5a9f487b8c0d647451ac0fd40046a

2025-01-06 13:55 UTC, elielnfinic commented
> This PR introduces a new asynchronous primitive for keeping track of the number of peers. While I am sure it improves the responsiveness and shrinks the window for race conditions, I am also concerned that it could also lead to inconsistent state and perhaps even deadlocks. @elielnfinic: please convince me that these concerns are unfounded. I also invite @dan-da to comment.
> 
> About the potential for deadlocks: I imagine this scenario
> 
> * thread 1: acquire a write lock on global state then (attempts to) modify `NUMBER_PEER_CONNECTIONS`
> * thread 2: read `NUMBER_PEER_CONNECTIONS` then modify global state
> * result: both stall indefinitely waiting for the other's lock to be released
> 
> About inconsistent state: the distance between modifications to the `peer_map` and corresponding modifications to `NUMBER_PEER_CONNECTIONS` is quite large and things can go wrong in the mean time. In that case, the first modification goes through but the second one doesn't.
> 
> One more thing: the sanity of operations that use the peer map is checked in unit tests that use `peer_map.len()` to count the number of entries. Is there a way to expand the tests or modify them so that they capture `NUMBER_PEER_CONNECTIONS`? This line of though suggests that the variable should not be a static variable but live somewhere, perhaps on `GlobalStateLock`, which might even be extended with an accessor method `get_num_peer_connections()`.

While I might be wrong, I believe the atomic operations I implemented will not create deadlocks with the global state, as atomic operations are inherently lock-free and do not create traditional locks. I have used the strongest ordering (SeqCst) to ensure that updates to NUMBER_PEER_CONNECTIONS always have a higher ordering than other operations. In the scenario you described, a deadlock could occur if NUMBER_PEER_CONNECTIONS were implemented using a Mutex or RwLock, but that is not the case here.

Regarding the potential for inconsistent state: I agree that the distance between modifications to the peer map and NUMBER_PEER_CONNECTIONS is non-trivial. However, when we create the “disconnect longest-lived peer” task, it will always be executed, even if it takes some time to process. Decrementing NUMBER_PEER_CONNECTIONS beforehand allows for a quicker response, instead of waiting for the task to complete. While this does introduce a window for inconsistency, it should remain minimal, given the guaranteed execution of the task.

On updating the test functions: If this flow is approved, I will proceed to update the test functions to reflect the new atomic logic, ensuring they capture both peer_map.len() and NUMBER_PEER_CONNECTIONS for consistency.

Lastly, I’m open to discussing the idea of moving NUMBER_PEER_CONNECTIONS into the GlobalStateLock with an accessor method like get_num_peer_connections(). This could align better with the overall design and make the variable’s management more cohesive.

2025-01-06 18:23 UTC, dan-da commented
> * thread 1: acquire a write lock on global state then (attempts to) modify `NUMBER_PEER_CONNECTIONS`
> * thread 2: read `NUMBER_PEER_CONNECTIONS` then modify global state

in sequential order, one scenario that fits above:

thread 1: acquire global-state write lock
thread 2: atomically read NUMBER_PEER_CONNECTIONS
thread 2: try-acquire global-state write-lock, wait
thread 1: atomically modify NUMBER_PEER_CONNECTIONS
thread 1: release global-state write-lock
thread 2: acquire global-state write-lock
thread 2: modify global state
thread 3: release global-state write-lock.

I don't see a problem here.

note: I have not reviewed the PR, just commenting on this particular aspect.

2025-01-09 16:08 UTC, aszepieniec commented
Thanks for the elaborate response. I appreciate the lesson.

Given that f6ed30f solves the problem as far as we know, the benefit of the extra proposed changes is marginal: potentially even better responsiveness at the exchange of more and potentially inconsistent state.

In order to justify spending time on this strategy, one would need to show that either
 - a) the issue persists despite f6ed30f; or
 - b) responsiveness is an issue in practice.

If there is no evidence to either of these points, I would suggest marking this issue resolved and devoting attention to something else.

2025-01-10 08:06 UTC, elielnfinic commented
I agree, with that PR, this needs to be closed.

2025-01-10 08:07 UTC, closed without merging